{% set data = load_setup_py_data() %}

package:
  name: indexed_bzip2
  version: {{ data.get('version') }}

# 'git_url' has the problem that I cannot specify a subfolder for the setup.py.
# 'path' fails to work because the relative symlinks in python/indexed_bzip2 are copied as is rendering them unusable.
# The created sdist tar correctly dereferences all symbolic links and therefore works but we need to rename the
# <package>-<major>-<minor>-<patch>.tar.gz to src.tar in order to avoid having to edit this file on each version change.
source:
  url: src.tar

build:
  entry_points:
    - ibzip2=indexed_bzip2:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - cython
    - {{ compiler('cxx') }}
    - cxxopts>=3,<4
    - setuptools >=61.2
    - wheel
  host:
    - python {{ python }}
    - setuptools >=61.2
    - wheel
    - cython
    - pip
    - cxxopts>=3,<4
  run:
    - {{ pin_compatible("libcxx", max_pin=None) }}  # [osx]

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_family: MIT
  license_file:
   - LICENSE-APACHE
   - LICENSE-MIT
  summary: {{ data.get('description') }}

extra:
  recipe-maintainers:
    - mxmlnkn
